#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("timeDifferencesToPauses() works", {

  expect_error(
    kwb.event:::timeDifferencesToPauses()
    # Argument "timeDifferences" fehlt (ohne Standardwert)
  )

})

