#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".deleteItemsRandomly() works", {

  expect_error(
    kwb.event:::.deleteItemsRandomly()
    # Argument "x" fehlt (ohne Standardwert)
  )

})

