#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("analyseEventRelations() works", {

  expect_error(
    kwb.event:::analyseEventRelations()
    # Argument "eventRelations" fehlt (ohne Standardwert)
  )

})

