#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getSignalWidth() works", {

  expect_error(
    kwb.event:::.getSignalWidth()
    # Argument "events" fehlt (ohne Standardwert)
  )

})

