#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("ganttPlotEventLists() works", {

  expect_error(
    kwb.event:::ganttPlotEventLists()
    # Argument "eventLists" fehlt (ohne Standardwert)
  )

})

