#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".hsShowEvents() works", {

  expect_error(
    kwb.event:::.hsShowEvents()
    # Argument "evts" fehlt (ohne Standardwert)
  )

})

