#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("eventsByState() works", {

  expect_error(
    kwb.event:::eventsByState()
    # Argument "timestamps" fehlt (ohne Standardwert)
  )

})

