#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".removeAndWarnIfColumnExists() works", {

  expect_error(
    kwb.event:::.removeAndWarnIfColumnExists()
    # Argument "columnName" fehlt (ohne Standardwert)
  )

})

