#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getEventsWithStatisticsForMultipleSeries() works", {

  expect_error(
    kwb.event:::getEventsWithStatisticsForMultipleSeries()
    # Argument "rainData" fehlt (ohne Standardwert)
  )

})

