#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".replaceZeroWithOne() works", {

  expect_error(
    kwb.event:::.replaceZeroWithOne()
    # Argument "x" fehlt (ohne Standardwert)
  )

})

