#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plotEventProperty1VersusEventProperty2() works", {

  expect_error(
    kwb.event:::plotEventProperty1VersusEventProperty2()
    # Argument "events" fehlt (ohne Standardwert)
  )

})

