#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readEventFilesFromDirectory() works", {

  expect_error(
    kwb.event:::readEventFilesFromDirectory()
    # Argument "event.dir" fehlt (ohne Standardwert)
  )

})

