#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getDurationIfPossible() works", {

  expect_error(
    kwb.event:::.getDurationIfPossible()
    # Argument "sigWidth" fehlt (ohne Standardwert)
  )

})

