#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsJoinEvents() works", {

  expect_error(
    kwb.event:::hsJoinEvents()
    # Argument "evts" fehlt (ohne Standardwert)
  )

})

