#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getAndFilterEventsWithStatistics() works", {

  expect_error(
    kwb.event:::getAndFilterEventsWithStatistics()
    # Argument "rainData" fehlt (ohne Standardwert)
  )

})

