#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("whichAboveThreshold() works", {

  expect_error(
    kwb.event:::whichAboveThreshold()
    # Argument "comparisonOperator" fehlt (ohne Standardwert)
  )

})

