#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getXLimFromEventLists() works", {

  expect_error(
    kwb.event:::getXLimFromEventLists()
    # Argument "eventLists" fehlt (ohne Standardwert)
  )

})

