#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".propertyWarning() works", {

  expect_error(
    kwb.event:::.propertyWarning()
    # Argument "propertyName" fehlt (ohne Standardwert)
  )

})

