#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".intervalSequenceIsValid() works", {

  expect_error(
    kwb.event:::.intervalSequenceIsValid()
    # Argument "fromTo" fehlt (ohne Standardwert)
  )

})

