#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".bindRowsWithinIndexes() works", {

  expect_error(
    kwb.event:::.bindRowsWithinIndexes()
    # Argument "i" fehlt (ohne Standardwert)
  )

})

