#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getEventStatistics() works", {

  expect_error(
    kwb.event:::getEventStatistics()
    # Argument "seriesName" fehlt (ohne Standardwert)
  )

})

