#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsMergeEvents() works", {

  expect_error(
    kwb.event:::hsMergeEvents()
    # Argument "events2" fehlt (ohne Standardwert)
  )

})

