#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsEvents() works", {

  expect_error(
    kwb.event:::hsEvents()
    # Argument "tseries" fehlt (ohne Standardwert)
  )

})

