#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("eventDuration() works", {

  expect_error(
    kwb.event:::eventDuration()
    # Argument "tEnd" fehlt (ohne Standardwert)
  )

})

