#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".printOnDebug() works", {

  expect_error(
    kwb.event:::.printOnDebug()
    # Argument "debug" fehlt (ohne Standardwert)
  )

})

