#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("mergeAllEvents() works", {

  expect_error(
    kwb.event:::mergeAllEvents()
    # Argument "eventList" fehlt (ohne Standardwert)
  )

})

