#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".withRowsRenumberedIfTrue() works", {

  expect_error(
    kwb.event:::.withRowsRenumberedIfTrue()
    # Argument "renumber" fehlt (ohne Standardwert)
  )

})

