#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("eventToXLim() works", {

  expect_error(
    kwb.event:::eventToXLim()
    # Argument "event" fehlt (ohne Standardwert)
  )

})

