#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("eventRelation() works", {

  expect_error(
    kwb.event:::eventRelation()
    # Argument "event1" fehlt (ohne Standardwert)
  )

})

