#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsEventsOnChange() works", {

  expect_error(
    kwb.event:::hsEventsOnChange()
    # Argument "x" fehlt (ohne Standardwert)
  )

})

