#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("toEvents() works", {

  expect_error(
    kwb.event:::toEvents()
    # Argument "events" fehlt (ohne Standardwert)
  )

})

