#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readEventsFromFile() works", {

  expect_error(
    kwb.event:::readEventsFromFile()
    # Argument "file" fehlt (ohne Standardwert)
  )

})

