#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("filterEventsWithStatistics() works", {

  expect_error(
    kwb.event:::filterEventsWithStatistics()
    # Argument "eventData" fehlt (ohne Standardwert)
  )

})

