#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".joinSubEvents() works", {

  expect_error(
    kwb.event:::.joinSubEvents()
    # Argument "sub.events" fehlt (ohne Standardwert)
  )

})

