#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".stopOnUnknownTimeUnit() works", {

  expect_error(
    kwb.event:::.stopOnUnknownTimeUnit()
    # Argument "timeUnit" fehlt (ohne Standardwert)
  )

})

