#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getSecondsPerTimeUnitOrStop() works", {

  expect_error(
    kwb.event:::.getSecondsPerTimeUnitOrStop()
    # Argument "timeUnit" fehlt (ohne Standardwert)
  )

})

